#!/bin/sh
# ARC XT — Pre-Commit Hook (Layer 2: Git Hard Gate)
# Auto-generated by ARC XT extension. Do not edit manually.
# Installs to: .git/hooks/pre-commit
# Source: .arc/hooks/pre-commit.sh

set -e

ARC_DIR="$(git rev-parse --show-toplevel)/.arc"
AUDIT_FILE="$ARC_DIR/audit.jsonl"
AUTH_FILE="$ARC_DIR/auth-state.json"

# If no .arc directory, ARC is not active — allow commit
if [ ! -d "$ARC_DIR" ]; then
  exit 0
fi

# If no audit log, no governed saves have occurred — allow commit
if [ ! -f "$AUDIT_FILE" ]; then
  exit 0
fi

# Check for unauthorized saves since last commit
# Look for audit entries with decision=REQUIRE_PLAN that have no linked blueprint
# Format: each line is JSON with "decision" and "blueprint_id" fields

UNAUTHORIZED=0
UNAUTHORIZED_FILES=""

# Read staged files and check against audit log
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM 2>/dev/null || true)

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

for FILE in $STAGED_FILES; do
  # Check if this file has an unauthorized REQUIRE_PLAN entry in the audit log
  # Look for lines where decision="REQUIRE_PLAN" and blueprint_id is null/missing
  UNAUTH_COUNT=$(grep "\"file_path\":\"[^\"]*$(echo "$FILE" | sed 's/[.[\*^$()+?{|\\]/\\&/g')\"" "$AUDIT_FILE" 2>/dev/null | grep '"decision":"REQUIRE_PLAN"' 2>/dev/null | grep -v '"blueprint_id":"[^"]*"' 2>/dev/null | wc -l || echo "0")

  if [ "$UNAUTH_COUNT" -gt 0 ]; then
    UNAUTHORIZED=1
    if [ -n "$UNAUTHORIZED_FILES" ]; then
      UNAUTHORIZED_FILES="$UNAUTHORIZED_FILES
  - $FILE"
    else
      UNAUTHORIZED_FILES="  - $FILE"
    fi
  fi
done

# If no unauthorized saves, allow commit
if [ "$UNAUTHORIZED" -eq 0 ]; then
  exit 0
fi

# Check if auth state file exists and shows all resolves
if [ -f "$AUTH_FILE" ]; then
  # Check if there are any unresolved require_plan entries
  UNRESOLVED=$(grep -c '"resolved":false' "$AUTH_FILE" 2>/dev/null || echo "0")
  if [ "$UNRESOLVED" -eq 0 ]; then
    exit 0
  fi
fi

# Block commit with clear message
cat <<EOF

╔══════════════════════════════════════════════════════════╗
║  ARC XT: Commit Blocked                                 ║
╠══════════════════════════════════════════════════════════╣
║                                                          ║
║  The following staged files need a linked blueprint:     ║
$UNAUTHORIZED_FILES
║                                                          ║
║  Link a blueprint before committing:                     ║
║    1. Open ARC XT Panel                                  ║
║    2. Link a blueprint for each file                     ║
║    3. Retry commit                                     ║
║                                                          ║
║  To bypass (not recommended):                            ║
║    git commit --no-verify                                ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝

EOF

exit 1
